# Generated by Django 6.0.6 on 2026-06-17 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Tadbir nomi')),
                ('theme', models.CharField(blank=True, max_length=256, verbose_name='Mavzu')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('date', models.CharField(max_length=32, verbose_name='Sana')),
                ('time', models.CharField(max_length=16, verbose_name='Vaqt')),
                ('location', models.CharField(max_length=256, verbose_name='Manzil')),
                ('latitude', models.CharField(blank=True, max_length=32, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=32, verbose_name='Longitude')),
                ('speaker', models.CharField(blank=True, max_length=256, verbose_name='Speaker')),
                ('category', models.CharField(choices=[('conference', 'Konferensiya'), ('workshop', 'Workshop'), ('networking', 'Networking'), ('other', 'Boshqa')], default='other', max_length=32, verbose_name='Kategoriya')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Rasm')),
                ('send_to_all_users', models.BooleanField(default=True, verbose_name='Hamma foydalanuvchiga yuborilsin')),
                ('send_at', models.DateTimeField(blank=True, null=True, verbose_name='Avtomatik yuborish vaqti')),
                ('sent', models.BooleanField(default=False, verbose_name='Yuborilgan')),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send_groups', models.ManyToManyField(blank=True, related_name='events', to='groups.group', verbose_name='Yuboriladigan guruhlar')),
            ],
            options={
                'verbose_name': 'Tadbir',
                'verbose_name_plural': 'Tadbirlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_at', models.DateTimeField(verbose_name='Eslatma vaqti')),
                ('label', models.CharField(default='Eslatma', max_length=256, verbose_name='Eslatma matni')),
                ('sent', models.BooleanField(default=False, verbose_name='Yuborilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='events.event', verbose_name='Tadbir')),
            ],
            options={
                'verbose_name': 'Tadbir eslatmasi',
                'verbose_name_plural': 'Tadbir eslatmalari',
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp_choice', models.CharField(choices=[('yes', 'Boraman'), ('no', 'Bormayman'), ('unknown', 'Javob bermagan')], default='unknown', max_length=16, verbose_name='Javobi')),
                ('is_attendance', models.BooleanField(default=False, verbose_name='Tadbirga keldi (QR skan)')),
                ('message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Botda yuborilgan xabar ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='events.event', verbose_name='Tadbir')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_responses', to='users.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi javobi',
                'verbose_name_plural': 'Foydalanuvchi javoblari',
                'unique_together': {('user', 'event')},
            },
        ),
    ]
