# Generated by Django 5.2 on 2026-06-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='rsvp_choice',
            field=models.CharField(choices=[('boraman', 'Boraman'), ('balki_borarman', 'Balki borarman'), ('balki_bormasman', 'Balki bormasman'), ('bormayman', 'Bormayman'), ('unknown', 'Javob bermagan')], default='unknown', max_length=16, verbose_name='Javobi'),
        ),
    ]
