# Generated by Django 5.2 on 2026-06-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_userevent_rsvp_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='telegraph_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
