# Generated by Django 5.2 on 2026-06-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_telegraph_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Joy nomi')),
                ('address', models.CharField(blank=True, max_length=512, verbose_name="To'liq manzil")),
                ('latitude', models.CharField(blank=True, max_length=32, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=32, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Manzil',
                'verbose_name_plural': 'Manzillar',
                'ordering': ['name'],
            },
        ),
    ]
