# Generated by Django 5.2 on 2026-06-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='use_auto_template',
            field=models.BooleanField(default=False, verbose_name='Avtomatik shablon (Assalamu alaykum...)'),
        ),
    ]
