# Generated by Django 5.2.15 on 2026-07-14 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_use_auto_template'),
        ('groups', '0001_initial'),
        ('users', '0005_alter_userprofile_nda_alter_userprofile_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('user', 'Foydalanuvchi'), ('group', 'Guruh')], max_length=8, verbose_name='Kimga')),
                ('chat_id', models.CharField(max_length=64, verbose_name='Chat ID')),
                ('message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Xabar ID')),
                ('status', models.CharField(choices=[('success', 'Yuborildi'), ('failed', 'Xato')], default='failed', max_length=8, verbose_name='Holati')),
                ('error', models.TextField(blank=True, verbose_name='Xato matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='events.event', verbose_name='Tadbir')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_send_logs', to='groups.group', verbose_name='Guruh')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_send_logs', to='users.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Yuborish jurnali',
                'verbose_name_plural': 'Yuborish jurnallari',
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('event', 'user'), name='uniq_event_user_log'), models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('event', 'group'), name='uniq_event_group_log')],
            },
        ),
    ]
