# Generated by Django 5.2.15 on 2026-08-06 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventsendlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256, verbose_name='Ism familiya')),
                ('phone', models.CharField(max_length=32, verbose_name='Telefon raqam')),
                ('note', models.CharField(blank=True, max_length=256, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='events.event', verbose_name='Tadbir')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Ledlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
