# Generated by Django 5.2.15 on 2026-08-17 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('contacted', "Bog'lanildi"), ('thinking', "O'ylayapti"), ('joined', "Mijoz bo'ldi"), ('rejected', 'Rad etdi')], default='new', max_length=16, verbose_name='Holat'),
        ),
        migrations.AddField(
            model_name='lead',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Holat o'zgargan vaqt"),
        ),
        migrations.CreateModel(
            name='LeadStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=16, verbose_name='Eski holat')),
                ('new_status', models.CharField(max_length=16, verbose_name='Yangi holat')),
                ('changed_by', models.CharField(blank=True, max_length=128, verbose_name="Kim o'zgartirdi")),
                ('note', models.CharField(blank=True, max_length=256, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='events.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Lead holat tarixi',
                'verbose_name_plural': 'Lead holat tarixlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
