# Generated by Django 5.2 on 2026-09-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_lead_status_lead_status_changed_at_leadstatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='follow_up_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Qayta aloqa eslatmasi'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('contacted', "Bog'lanildi"), ('follow_up', 'Qayta aloqaga chiqish'), ('thinking', "O'ylayapti"), ('joined', "Mijoz bo'ldi"), ('rejected', 'Rad etdi')], default='new', max_length=16, verbose_name='Holat'),
        ),
    ]
