# Generated by Django 5.2.15 on 2026-09-28 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_calendarevent'),
        ('workers', '0014_workevent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='work_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_event', to='workers.workevent', verbose_name='Ishchilar tadbiri'),
        ),
    ]
