# Generated by Django 5.2.15 on 2026-09-02 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_tripssendlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Safar nomi')),
                ('note', models.CharField(blank=True, max_length=256, verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Safar',
                'verbose_name_plural': 'Safarlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=256, verbose_name='F.I.O.')),
                ('status', models.CharField(blank=True, choices=[('mlp', 'MLP'), ('mbc', 'MBC'), ('yangi', 'Yangi'), ('org_team', 'ORG Team'), ('pul_ilmi', 'Yangi / Pul ilmi'), ('mehmon', 'Mehmon'), ('speaker', 'Speaker')], max_length=16, verbose_name='Statusi')),
                ('travel_status', models.CharField(blank=True, choices=[('confirmed', 'Confirmed'), ('80_20', '80/20'), ('50_50', '50/50'), ('declined', 'Declined'), ('self', 'Self'), ('51_49', '51/49')], max_length=16, verbose_name='Safarga borish')),
                ('subscription', models.CharField(blank=True, choices=[('bor', 'Bor'), ('yoq', "Yo'q"), ('kelib', 'Kelib oladilar')], max_length=16, verbose_name='Yillik podpiska')),
                ('payment_status', models.CharField(blank=True, choices=[('berdi', 'Berdi'), ('avans', 'Avans berdi'), ('kutilmoqda', 'Kutilmoqda'), ('otkaz', 'Otkaz'), ('self', 'Self'), ('omonatdan', 'Omonatdan'), ('rasxod', 'Rasxod')], max_length=16, verbose_name="To'lov")),
                ('entry_sum', models.BigIntegerField(default=0, verbose_name='Vxodnoy summasi')),
                ('trip_sum', models.BigIntegerField(default=0, verbose_name='Safar summasi (umumiy)')),
                ('deposit', models.BigIntegerField(default=0, verbose_name='Omonatdan')),
                ('paid', models.BigIntegerField(default=0, verbose_name='Berdi')),
                ('comment', models.TextField(blank=True, verbose_name='Kommentariya')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='trips.trip', verbose_name='Safar')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_participations', to='users.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Safar qatnashuvchisi',
                'verbose_name_plural': 'Safar qatnashuvchilari',
                'ordering': ['order', 'id'],
            },
        ),
    ]
