# Generated by Django 5.2.15 on 2026-09-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='country',
            field=models.CharField(blank=True, help_text="Profilga yoziladigan nom (masalan: Fukok). Bo'sh bo'lsa safar nomi ishlatiladi.", max_length=128, verbose_name="Davlat / yo'nalish"),
        ),
    ]
