# Generated by Django 5.2.15 on 2026-09-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name="Davlat / yo'nalish")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Davlat (safar)',
                'verbose_name_plural': 'Davlatlar (safar)',
                'ordering': ['name'],
            },
        ),
    ]
