# Generated by Django 5.2 on 2026-09-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_seed_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripparticipant',
            name='went',
            field=models.BooleanField(default=False, verbose_name='Bordi'),
        ),
    ]
