# Generated by Django 5.2 on 2026-09-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_tripparticipant_went'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripparticipant',
            name='follow_up_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Qayta aloqaga eslatmasi'),
        ),
        migrations.AlterField(
            model_name='tripparticipant',
            name='travel_status',
            field=models.CharField(blank=True, choices=[('confirmed', 'Confirmed'), ('80_20', '80/20'), ('50_50', '50/50'), ('declined', 'Declined'), ('self', 'Self'), ('51_49', '51/49'), ('follow_up', 'Qayta aloqaga chiqish')], max_length=16, verbose_name='Safarga borish'),
        ),
    ]
