# Generated by Django 6.0.6 on 2026-06-17 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Xabar matni')),
                ('tags', models.JSONField(default=list, verbose_name='Kimga yuborilsin (teglar)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SendMessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='messages/', verbose_name='Fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='messages_app.sendmessage', verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Xabar fayli',
                'verbose_name_plural': 'Xabar fayllari',
            },
        ),
        migrations.CreateModel(
            name='SendMessageUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('success', 'Yuborildi'), ('failed', 'Xato')], default='pending', max_length=16, verbose_name='Holati')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Xato matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='messages_app.sendmessage', verbose_name='Xabar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Xabar holati',
                'verbose_name_plural': 'Xabar holatlari',
            },
        ),
    ]
