# Generated by Django 6.0.6 on 2026-06-17 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=64, unique=True, verbose_name='Telegram ID')),
                ('tg_username', models.CharField(blank=True, max_length=128, null=True, verbose_name='Telegram username')),
                ('tg_phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='Telefon raqam')),
                ('role', models.CharField(choices=[('user', 'Foydalanuvchi'), ('admin', 'Admin')], default='user', max_length=32, verbose_name='Rol')),
                ('user_unique_code', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='QR kod')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Ism')),
                ('surname', models.CharField(blank=True, max_length=128, verbose_name='Familiya')),
                ('birth_date', models.CharField(blank=True, max_length=10, verbose_name="Tug'ilgan sana")),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Telefon')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photos/', verbose_name='Rasm')),
                ('birth_place', models.CharField(blank=True, max_length=128, verbose_name="Tug'ilgan joy")),
                ('work_location', models.CharField(blank=True, max_length=128, verbose_name='Ish/yashash shahri')),
                ('industry', models.CharField(blank=True, max_length=128, verbose_name='Faoliyat sohasi')),
                ('company_role', models.CharField(blank=True, max_length=128, verbose_name='Kompaniyadagi lavozimi')),
                ('brand', models.CharField(blank=True, max_length=128, verbose_name='Brend/kompaniya nomi')),
                ('website', models.CharField(blank=True, max_length=256, verbose_name='Vebsayt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi profili',
                'verbose_name_plural': 'Foydalanuvchi profillari',
            },
        ),
    ]
