# Generated by Django 5.2 on 2026-06-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unique_id',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='4 xonali ID'),
        ),
    ]
