# Generated by Django 5.2 on 2026-06-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.TextField(blank=True, verbose_name='Biznes maqsadi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram',
            field=models.CharField(blank=True, max_length=128, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='join_date',
            field=models.CharField(blank=True, max_length=10, verbose_name="Klubga qo'shilgan sana"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list, verbose_name='Tillar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nda',
            field=models.CharField(blank=True, max_length=8, verbose_name='NDA roziligi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='problems',
            field=models.TextField(blank=True, verbose_name='Biznesdagi qiyinchiliklar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reason',
            field=models.TextField(blank=True, verbose_name="Qo'shilish sababi"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selected_trips',
            field=models.JSONField(blank=True, default=list, verbose_name='Safarlar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='staff_count',
            field=models.CharField(blank=True, max_length=64, verbose_name='Xodimlar soni'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='turnover',
            field=models.CharField(blank=True, max_length=64, verbose_name='Yillik aylanma'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visit',
            field=models.CharField(blank=True, max_length=8, verbose_name='Kompaniya tashrifi'),
        ),
    ]
