# Generated by Django 5.2 on 2026-07-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nda',
            field=models.CharField(blank=True, max_length=50, verbose_name='NDA roziligi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='visit',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kompaniya tashrifi'),
        ),
    ]
