# Generated by Django 5.2.15 on 2026-08-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_nda_alter_userprofile_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
