# Generated by Django 5.2 on 2026-08-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sent_to_trips_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Safarlar guruhiga yuborilgan'),
        ),
    ]
