# Generated by Django 5.2.15 on 2026-08-19 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_sent_to_trips_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripsSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_member', models.BooleanField(default=False, verbose_name="Guruhda a'zo edi")),
                ('success', models.BooleanField(default=True, verbose_name='Muvaffaqiyatli')),
                ('error', models.CharField(blank=True, max_length=256, verbose_name='Xato matni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_send_logs', to='users.userprofile', verbose_name='Profil')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_sends', to=settings.AUTH_USER_MODEL, verbose_name='Kim yubordi')),
            ],
            options={
                'verbose_name': 'Safarlarga yuborish jurnali',
                'verbose_name_plural': 'Safarlarga yuborish jurnallari',
                'ordering': ['-created_at'],
            },
        ),
    ]
