# Generated by Django 6.0.6 on 2026-06-17 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Vazifa nomi')),
                ('days_before', models.IntegerField(verbose_name='Necha kun oldin')),
                ('hours_before', models.IntegerField(blank=True, null=True, verbose_name='Necha soat oldin')),
                ('deadline_date', models.DateField(verbose_name='Deadline sanasi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Bajarildi'), ('overdue', 'Kechikdi')], default='pending', max_length=20, verbose_name='Holati')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Eslatma yuborilgan')),
                ('instruction', models.TextField(blank=True, null=True, verbose_name='Instruksiya')),
            ],
            options={
                'verbose_name': 'Vazifa',
                'verbose_name_plural': 'Vazifalar',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Shablon nomi')),
            ],
            options={
                'verbose_name': 'Shablon',
                'verbose_name_plural': 'Shablonlar',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ismi')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('worker', 'Ishchi'), ('boss', 'Boshliq')], max_length=20, verbose_name='Roli')),
            ],
            options={
                'verbose_name': 'Ishchi',
                'verbose_name_plural': 'Ishchilar',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='workers.task')),
            ],
            options={
                'verbose_name': 'Xabar logi',
                'verbose_name_plural': 'Xabar loglari',
            },
        ),
        migrations.CreateModel(
            name='TemplateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Vazifa nomi')),
                ('days_before', models.IntegerField(verbose_name='Necha kun oldin')),
                ('hours_before', models.IntegerField(blank=True, help_text='Masalan: 2 — tadbirdan 2 soat oldin', null=True, verbose_name='Necha soat oldin (ixtiyoriy)')),
                ('instruction', models.TextField(blank=True, null=True, verbose_name='Instruksiya')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workers.template', verbose_name='Shablon')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker', verbose_name='Ishchi')),
            ],
            options={
                'verbose_name': 'Shablon vazifasi',
                'verbose_name_plural': 'Shablon vazifalari',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker', verbose_name='Ishchi'),
        ),
        migrations.CreateModel(
            name='WorkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tadbir nomi')),
                ('event_date', models.DateField(verbose_name='Tadbir sanasi')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='Tadbir vaqti')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.template', verbose_name='Shablon')),
            ],
            options={
                'verbose_name': 'Ishchilar tadbiri',
                'verbose_name_plural': 'Ishchilar tadbirlari',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workers.workevent', verbose_name='Tadbir'),
        ),
    ]
