# Generated by Django 5.2.15 on 2026-07-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='when',
            field=models.CharField(choices=[('before', 'oldin'), ('after', 'keyin')], default='before', max_length=8, verbose_name='Tadbirdan oldin/keyin'),
        ),
        migrations.AddField(
            model_name='templatetask',
            name='when',
            field=models.CharField(choices=[('before', 'oldin'), ('after', 'keyin')], default='before', max_length=8, verbose_name='Tadbirdan oldin/keyin'),
        ),
        migrations.AlterField(
            model_name='task',
            name='days_before',
            field=models.IntegerField(verbose_name='Necha kun'),
        ),
        migrations.AlterField(
            model_name='templatetask',
            name='days_before',
            field=models.IntegerField(verbose_name='Necha kun'),
        ),
    ]
