# Generated by Django 5.2.15 on 2026-08-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_task_when_templatetask_when_alter_task_days_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Tadbir vaqti (2 soat) eslatmasi yuborilgan'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Deadline eslatmasi yuborilgan'),
        ),
    ]
