# Generated by Django 5.2 on 2026-08-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_task_time_reminder_sent_alter_task_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='role',
            field=models.CharField(choices=[('worker', 'Ishchi'), ('boss', 'Boshliq')], default='boss', max_length=10, verbose_name='Kimga yuborilgan'),
        ),
    ]
