# Generated by Django 5.2 on 2026-09-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_task_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='department',
            field=models.CharField(blank=True, choices=[('media', '📱 Media'), ('organizator', '🎯 Organizator'), ('ceo', '👔 CEO'), ('menejer', '💼 Menejer')], max_length=20, verbose_name="Bo'lim"),
        ),
    ]
