# Generated by Django 5.2 on 2026-09-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_worker_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='workevent',
            name='checklist_chat_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Check-list chat ID'),
        ),
        migrations.AddField(
            model_name='workevent',
            name='checklist_message_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Check-list xabar ID'),
        ),
    ]
