# Generated by Django 5.2.15 on 2026-09-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_workevent_checklist_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workevent',
            name='checklist_note',
            field=models.CharField(blank=True, max_length=200, verbose_name="Check-list tepasidagi 'Yangilandi' izohi"),
        ),
    ]
