# Generated by Django 5.2.15 on 2026-09-23 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_workevent_checklist_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='workers.worker', verbose_name='Kim biriktirdi (boshliq)'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan vaqt'),
        ),
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.CharField(choices=[('site', 'Sayt (tadbir)'), ('boss', "Boshliq topshirig'i")], default='site', max_length=8, verbose_name='Manba'),
        ),
        migrations.AlterField(
            model_name='task',
            name='days_before',
            field=models.IntegerField(default=0, verbose_name='Necha kun'),
        ),
        migrations.AlterField(
            model_name='task',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workers.workevent', verbose_name='Tadbir'),
        ),
    ]
