# Generated by Django 5.2 on 2026-09-24 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0010_task_assigned_by_task_completed_at_task_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20, verbose_name="Bo'lim")),
                ('chat_id', models.CharField(max_length=64, verbose_name='Chat ID')),
                ('message_id', models.BigIntegerField(verbose_name='Xabar ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_messages', to='workers.workevent', verbose_name='Tadbir')),
            ],
            options={
                'verbose_name': 'Check-list xabari',
                'verbose_name_plural': 'Check-list xabarlari',
                'unique_together': {('event', 'department')},
            },
        ),
    ]
