# Generated by Django 5.2.15 on 2026-09-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0011_checklistmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Bajarildi'), ('overdue', 'Kechikdi'), ('not_done', 'Bajarilmadi')], default='pending', max_length=20, verbose_name='Holati'),
        ),
    ]
