# Generated by Django 5.2.15 on 2026-09-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0012_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_head',
            field=models.BooleanField(default=False, help_text="Belgilansa, check-listda ismi tepasida '<Bo'lim> boshlig'i' bo'lib chiqadi. Botga kirish huquqi 'Roli' orqali belgilanadi — bunga bog'liq emas.", verbose_name="Bo'lim boshlig'i (check-list uchun)"),
        ),
    ]
