# Generated by Django 5.2.15 on 2026-09-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0013_worker_is_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='workevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Tasdiq kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='approved', max_length=10, verbose_name='Holati'),
        ),
    ]
