# Generated by Django 5.2 on 2026-09-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0014_workevent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workevent',
            name='rejection_seen',
            field=models.BooleanField(default=False, verbose_name="Rad etish bildirishnomasi ko'rildi"),
        ),
    ]
